name: py36
channels:
- defaults
dependencies:
- certifi=2016.2.28=py36_0
- cycler=0.10.0=py36_0
- freetype=2.5.5=2
- icu=54.1=0
- libpng=1.6.30=1
- matplotlib=2.0.2=np113py36_0
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.2=py36_0
- qt=5.6.2=2
- readline=6.2=2
- scipy=0.19.1=np113py36_0
- setuptools=36.4.0=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
prefix: /Users/emilyschlafly/anaconda/envs/py36

